# [global] section removed deprecated dataFrameSerialization

[server]
# Server settings
port = 8501
enableCORS = true
# If you want to disable XSRF protection, set enableXsrfProtection = false
maxUploadSize = 200
maxMessageSize = 200

[browser]
# Browser settings
gatherUsageStats = false

[theme]
# UI Theme
primaryColor = "#1f77b4"
backgroundColor = "#ffffff"
secondaryBackgroundColor = "#f0f2f6"
textColor = "#262730"
font = "sans serif"

# [client] section removed deprecated caching and displayEnabled